# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 200
format = "[${custom.distrobox}$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
substitutions = [
  { from = '^/var/home/[^/]+', to = '~', regex = true },
]


[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""


[custom.distrobox]
description = "Displays name of the activated distrobox container"
# box symbol from NerdFonts
symbol = ""

# activates when the command in "when" returns 0 (succeed / true)
# we check for the $CONTAINER_ID variable as described in https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#detect-if-youre-in-a-distrobox
when = "[ -n \"${CONTAINER_ID}\" ]"

# the output of this command will be provided in $output for the format
# here we get the name of the distrobox
command = "echo ${CONTAINER_ID}"

format = '\[[$symbol $output]($style)\] '

disabled=false

style = "bold green"
